/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/DogAnim.glb -t
*/
import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Blendshapes } from "../../apis/mediapipe_audio_blendshapes";
import * as talkingHead from "../../apis/talkingHead";
import { AnimationAction } from "three";

import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import * as SkeletonUtils from "three/examples/jsm/utils/SkeletonUtils";

type GLTFResult = GLTF & {
  nodes: {
    Briefcase: THREE.Bone;
    Chest: THREE.Bone;
    Collar: THREE.Bone;
    Collar1: THREE.Bone;
    Geometry: THREE.Object3D;
    Head: THREE.Bone;
    Hip: THREE.Bone;
    Jaw: THREE.Bone;
    L_Ankle: THREE.Bone;
    L_Arm: THREE.Bone;
    L_Ear1: THREE.Bone;
    L_Ear2: THREE.Bone;
    L_Ear3: THREE.Bone;
    L_Eye: THREE.Bone;
    L_Eyebrow_A: THREE.Bone;
    L_Eyebrow_B: THREE.Bone;
    L_Eyebrow_C: THREE.Bone;
    L_Finger: THREE.Bone;
    L_Finger_End: THREE.Bone;
    L_Foot: THREE.Bone;
    L_FootPrint: THREE.Bone;
    L_ForeArm: THREE.Bone;
    L_Hip: THREE.Bone;
    L_Leg: THREE.Bone;
    L_LowerEyelid: THREE.Bone;
    L_Shoulder: THREE.Bone;
    L_Toe: THREE.Bone;
    L_UpperEyelid: THREE.Bone;
    Neck: THREE.Bone;
    Nose: THREE.Bone;
    R_Ankle: THREE.Bone;
    R_Arm: THREE.Bone;
    R_Ear1: THREE.Bone;
    R_Ear2: THREE.Bone;
    R_Ear3: THREE.Bone;
    R_Eye: THREE.Bone;
    R_Eyebrow_A: THREE.Bone;
    R_Eyebrow_B: THREE.Bone;
    R_Eyebrow_C: THREE.Bone;
    R_Finger: THREE.Bone;
    R_Finger_End: THREE.Bone;
    R_Foot: THREE.Bone;
    R_FootPrint: THREE.Bone;
    R_ForeArm: THREE.Bone;
    R_Hip: THREE.Bone;
    R_Leg: THREE.Bone;
    R_LowerEyelid: THREE.Bone;
    R_Shoulder: THREE.Bone;
    R_Toe: THREE.Bone;
    R_UpperEyelid: THREE.Bone;
    Root: THREE.Bone;
    Rover: THREE.SkinnedMesh;
    Rover_Props: THREE.Object3D;
    Rover_footprint: THREE.SkinnedMesh;
    Rover_travel_bag: THREE.SkinnedMesh;
    Spine1: THREE.Bone;
    Spine2: THREE.Bone;
    Tail1: THREE.Bone;
    Tail2: THREE.Bone;
    Tail3: THREE.Bone;
    Tail4: THREE.Bone;
    Tongue1: THREE.Bone;
    Tongue2: THREE.Bone;
    Tongue3: THREE.Bone;
    Tongue4: THREE.Bone;
    Tongue5: THREE.Bone;


  };
  materials: {
   
  };
};
type ActionName = "Expression" | "KeyAction" | "_CharacterSucceeds" | "BodyAction";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;
function updateBlendshapes(
  node: THREE.Mesh,
  blendshapes: Blendshapes /* Map<string, number> */
) {
  if (!node.morphTargetDictionary) {
    return;
  }
  if (!node.morphTargetInfluences) {
    return;
  }
  // console.log(blendshapes)
  // console.log(node.morphTargetDictionary)
  for (const name in blendshapes) {
    const value = blendshapes[name];
    if (!Object.keys(node.morphTargetDictionary).includes(name)) {
      continue;
    }
    const idx = node.morphTargetDictionary[name];
    node.morphTargetInfluences[idx] = value;
  }
}
export function DogAnim({...props}) {
  const group = useRef<THREE.Group>();
  const object3D = useRef<THREE.Object3D>();
  const skinnedMesh = useRef<THREE.SkinnedMesh>();
  const bone = useRef<THREE.Bone>();

  const { nodes, materials, animations } = useGLTF(
    "/DogAnim.glb"
  ) as GLTFResult;
  
  const { ref, actions } = useAnimations(animations, group);

  
  console.log("------actions--------");
  console.log(actions);
  console.log("--------------");

  const keyactionsStoped = useRef<boolean>(false);
  useEffect(() => {
    setInterval(() => {
      if (talkingHead.audioBlendshapes === null) return;
      const blendShapesMapping = talkingHead.audioBlendshapes!.getBlendshapes();
      if (!keyactionsStoped.current && talkingHead.lastAudioT > 0.0) {
        actions.Idle!.stop();
        keyactionsStoped.current = true;
      }
      updateBlendshapes(nodes.Rover, blendShapesMapping);
    }, 50);
  }, [nodes]);
  useEffect(() => {
    actions._CharacterSucceeds!.play();
    if (talkingHead.lastAudioT === 0.0) {
      actions.Idle!.play();
    }
  });

  console.log('-----nodes------');
  console.log(nodes);
  console.log('-----------');

  return (
    <group ref={ref as React.Ref<THREE.Group>} {...props} dispose={null} position={[0, -1, 7]}>
        {/* <object3D name="Geometry" position={[0,0,0]} rotation={[0,0,0]} scale={[1,1,1]}> */}
          <ambientLight intensity={0.5} /> 
          <directionalLight intensity={1} position={[0, 10, 0]} /> 
          <primitive object={nodes.Root}></primitive>
          <skinnedMesh name="Rover" geometry={nodes.Rover.geometry} material={nodes.Rover.material} skeleton={nodes.Rover.skeleton}>
          </skinnedMesh>
          {/* <object3D name="Rover_Props" position={[0,0,0]} rotation={[0,0,0,]} scale={[1,1,1]}> */}
            {/* <skinnedMesh name="Rover_travel_bag" geometry={nodes.Rover_travel_bag.geometry} material={nodes.Rover_travel_bag.material} skeleton={nodes.Rover_travel_bag.skeleton} >
              <primitive object={nodes.Rover_travel_bag.skeleton.bones[0]}></primitive>
            </skinnedMesh> */}
            {/* <skinnedMesh name="Rover_footprint" geometry={nodes.Rover_footprint.geometry} material={nodes.Rover_footprint.material} position={[0,0,0]} rotation={[0,0,0]} scale={[1,1,1]} skeleton={nodes.Rover_footprint.skeleton} /> */}
          {/* </object3D> */}
        {/* </object3D>
        <bone name="Root" position={[0,0,0]} rotation={[0,0,0]} scale={[1,1,1]}>
          <bone name="Hip" position={[0.16, 0.19, -0.27]} rotation={[3.1,-1.01, -1.73]} scale={[0.99,1,1]}>
            <bone name="Spine1" position={[0.04, -0.03,-2.6]} rotation={[0.01, 0.01, -0.54]} scale={[1, 1, 0.99]}>
              <bone name="Spine2" position={[0.27, -0.00004, 0.01]} rotation={[0.10, -0.003, -0.03]} scale={[1, 1, 1]}>
                <bone name="Chest" position={[0.37, -0.004, -0.01]} rotation={[0.006, 0.01, 0.27]} scale={[1, 0.99, 1]}>
                  <bone name="Neck" position={[0.14, 0.00002, 1.17]} rotation={[-0.001, 0.009, 0.29]} scale={[0.99, 0.99, 1]}>
                    <bone name="Head" position={[0.14, -0.005, -0.00002]} rotation={[0.37, 0.07, -0.65]} scale={[0.999, 1,1]}>
                      <bone name="Jaw" position={[0.16, -0.2, -1.25]} rotation={[0,0,-2]} scale={[0.99,0.99,1]}>
                        <bone name="Tongue1" position={[0.05, -0.03, -1.36]} rotation={[-0.12, 0.197, 0.77]} scale={[2.13, 1.35, 1.6]}>
                          <bone name="Tongue2" position={[0.023, 0.0003, -2.04]} rotation={[-0.0001,-0.008, -0.124]} scale={[1.005, 0.995, 0.99]}>
                            <bone name="Tongue3" position={[0.023, 4.44, 0]} rotation={[-0.024, -0.134, -0.77]} scale={[1.19, 0.84, 0.996]}>
                              <bone name="Tongue4" position={[0.023, 0,0]} rotation={[-0.11, -0.57, -0.73]} scale={[1.22, 0.87, 0.94]}>
                                <bone name="Tongue5" position={[0.023, 0, -3.75]} rotation={[0,0,0]} scale={[0.47, 1, 1]} />
                              </bone>
                            </bone>
                          </bone>
                        </bone>
                      </bone>
                      <bone name="L_Eye" position={[0.31, -0.04, -0.11]} rotation={[1.68, 0.33, -1.62]} scale={[0.99, 1, 0.99]}></bone>
                      <bone name="R_Eye" position={[0.31, -0.04, 0.11]} rotation={[-1.46,-0.33, 1.62]} scale={[1,1,0.99]}></bone>
                      <bone name="Nose" position={[0.36,-0.33, -9.71]} rotation={[1.57, 0.51, -1.57]} scale={[1,1,1]}></bone>
                      <bone name="L_Ear1" position={[0.37, 0.13, -0.19]} rotation={[0.98, 0.42, -0.81]} scale={[1,1,1]}>
                        <bone name="L_Ear2" position={[0.15, 2.22, 1.387]} rotation={[-0.18, 0.28, -1.78]} scale={[1,1,1]}>
                          <bone name="L_Ear3" position={[0.145, 1.44, 8.32]} rotation={[-0.18, -0.17, 0.08]} scale={[1,1,0.99]}></bone>
                        </bone>
                      </bone>
                      <bone name="R_Ear1" position={[0.37, 0.13, 0.19]} rotation={[-0.91, -0.48, 2.43]} scale={[0.99, 0.99, 1]}>
                        <bone name="R_Ear2" position={[-0.14, 8.56, 5.03]} rotation={[-0.13, 0.29, -1.67]} scale={[1,0.99,1]}>
                          <bone name="R_Ear3" position={[-0.145, -0.000002, -0.000001]} rotation={[-0.15,-0.103, 0.15]} scale={[1,1,0.99]}></bone>
                        </bone>
                      </bone>
                      <bone name="L_UpperEyelid" position={[0.31, -0.04, -0.11]} rotation={[1.87, -0.05, -1.74]} scale={[1,1,1.000001]}></bone>
                      <bone name="L_LowerEyelid" position={[0.31, -0.04, -0.11]} rotation={[2.15, 1.02, 1.25]} scale={[1,1,1]}></bone>
                      <bone name="R_UpperEyelid" position={[0.31, -0.04, 0.113]} rotation={[-1.87, 0.05, 1.403]} scale={[0.99, 1, 1.0000001]}></bone>
                      <bone name="R_LowerEyelid" position={[0.313, -0.04, 0.113]} rotation={[-2.16, -1.01,-1.9]} scale={[0.99, 1, 1.0000001]}></bone>
                      <bone name="L_Eyebrow_A" position={[0.46, -0.09, -0.06]} rotation={[1.64, 0.48, -1.35]} scale={[0.99,1,0.99]}></bone>
                      <bone name="L_Eyebrow_B" position={[0.44, -0.077, -0.168]} rotation={[1.54, 0.51, -1.65]} scale={[1,0.99,0.99]}></bone>
                      <bone name="L_Eyebrow_C" position={[0.346, -0.082, -0.24]} rotation={[1.56, 0.51, -1.599]} scale={[1.000001,1,1.000001]}></bone>
                      <bone name="R_Eyebrow_A" position={[0.455, -0.095, 0.061]} rotation={[-1.63, -0.51, 1.72]} scale={[1,1,1]}></bone>
                      <bone name="R_Eyebrow_B" position={[0.444, -0.076, 0.17]} rotation={[-1.51,-0.49,1.408 ]} scale={[1,1,1]}></bone>
                      <bone name="R_Eyebrow_C" position={[0.346, -0.082, 0.236]} rotation={[-1.57, -0.51, 1.57]} scale={[1,1,1]}></bone>
                    </bone> 
                    <bone name="Collar" position={[0.078, 0.007,6.939]} rotation={[0,0,-1.78]} scale={[1,1,1]}>
                      <bone name="Collar1" position={[0.242,2.22, -5.55]} rotation={[-0.14, -0.16, -1.01]} scale={[0.99,0.99,0.99]}></bone>
                    </bone>
                  </bone>
                  <bone name="L_Shoulder" position={[-0.09, -0.12, -0.19]} rotation={[1.56, 0.53, 3.02]} scale={[1,1,1]}>
                    <bone name="L_Arm" position={[0.225,0, -1.665]} rotation={[0,-0.22,0]} scale={[1,1,1]}>
                      <bone name="L_ForeArm" position={[0.224, 8.33,6.66]} rotation={[-0.47, -0.13, 0.2]} scale={[0.99,1,1]}>
                        <bone name="L_Finger" position={[0.111, 5.274, -2.331]} rotation={[0.000003, -1.179, 0.000004]} scale={[0.99,1,0.99]}>
                          <bone name="L_Finger_End" position={[0.143, 2.776, 0]} rotation={[0,0,0]} scale={[1,1,1]}></bone>
                        </bone>
                      </bone>
                    </bone>
                  </bone>
                  <bone name="R_Shoulder" position={[-0.089, -0.121, 0.19]} rotation={[1.522, 0.836, 3.012]} scale={[1.005, 1,1]}>
                    <bone name="R_Arm" position={[0.225, 1.388, -1.937]} rotation={[0,-0.00002, 0]} scale={[1,1,1]}>
                      <bone name="R_ForeArm" position={[0.224, -8.33, 3.515]} rotation={[0.256, -0.074, -0.046]} scale={[0.995,0.999,0.999]}>
                        <bone name="R_Finger" position={[0.1114, -5.357, 2.111]} rotation={[-7.925, -1.08, -8.983]} scale={[0.99, 1, 0.99]}>
                          <bone name="R_Finger_End" position={[0.143, -1.388, 2.776]} rotation={[-7.146, 0,0]} scale={[1,1,1]}></bone>
                        </bone>
                      </bone>
                    </bone>
                  </bone>
                </bone>
              </bone>
            </bone>
            <bone name="L_Hip" position={[0.026, -0.042, -0.213]} rotation={[-1.88, 1.889, 0.692]} scale={[1,1,1]}>
              <bone name="L_Leg" position={[0.248, -8.33,0]} rotation={[-3.14, 0.568, -3.14]} scale={[0.99,1,0.99]}>
                <bone name="L_Foot" position={[0.286, -1.277, 1.11]} rotation={[2.898, -0.769, 2.892]} scale={[0.99,0.99,0.99]}>
                  <bone name="L_Ankle" position={[0.203, -1.11, -5.55]} rotation={[3.5557, 0.029,1.24]} scale={[1,1,1]}>
                    <bone name="L_Toe" position={[0.143, -5.55, 3.26]} rotation={[0,0,0]} scale={[1,1,1]}></bone>
                  </bone>
                </bone>
              </bone>
            </bone>
            <bone name="R_Hip" position={[0.257, -0.042, 0.213]} rotation={[-1.162, 1.126, -0.709]} scale={[1, 1,1]}>
              <bone name="R_Leg" position={[0.248, 3.33, 0]} rotation={[-3.141, 0.562, 3.142]} scale={[1,1,1]}>
                <bone name="R_Foot" position={[0.286, -7.55, 2.83]} rotation={[-2.77, -0.75, -2.84]} scale={[0.99, 0.99, 0.99]}>
                  <bone name="R_Ankle" position={[0.203, -2.498, 6.355]} rotation={[-6.512, 0.035, 2.515]} scale={[1,1,1]}>
                    <bone name="R_Toe" position={[0.143, -8.27, 7.717]} rotation={[1.095, 0, -0]} scale={[1,1,1]}></bone>
                  </bone>
                </bone>
              </bone>
            </bone>
            <bone name="Tail1" position={[-0.155, 0.084, -1.787]} rotation={[2.863, 0.147, -1.667]} scale={[0.99, 0.99, 0.99]}>
              <bone name="Tail2" position={[0.186, 8.604, -2.776]} rotation={[0.324, -0.111, -0.098]} scale={[0.99, 1,1]}>
                <bone name="Tail3" position={[0.154, -5.55, -2.776]} rotation={[0.071, 0.286, -0.04]} scale={[1,1,1]}>
                  <bone name="Tail4" position={[0.135, 6.939, 1.752]} rotation={[-0.037, 0.19, -0.054]} scale={[0.99,0.99,1]}></bone>
                </bone>
              </bone>
            </bone>
          </bone>
          <bone name="Briefcase" position={[0.004, 0.002, 0.013]} rotation={[0,0,0]} scale={[0.001, 0.001, 0.001]}></bone>
          <bone name="L_FootPrint" position={[0.185, 1.085, 0.923]} rotation={[-1.57, 0,0]} scale={[1,0.99,0.99]}></bone>
          <bone name="R_FootPrint" position={[-0.366, 1.082, 0.923]} rotation={[1.57, 0, -0]} scale={[1,0.99, 0.99]}></bone>
        </bone> */}
      </group>
    // </group>
  );
}
useGLTF.preload("/DogAnim.glb");
